version: "3.4"
services:
  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3-alpine"
    ports:
      - "5672"
    restart: unless-stopped
  heimdalld:
    build: &ref_0
      args:
        UPSTREAM_VERSION: v0.2.1-mainnet
      context: ./build/heimdall
      dockerfile: Dockerfile
    volumes:
      - "/home/meng/polygon/heimdall:/root/.heimdalld"
    ports:
      - "36656:26656"
      - "36657:26657"
    depends_on:
      - rabbitmq
    environment:
      - MONIKER=DAPPNodler
      - SNAPSHOT_DATE=2021-06-22
      - BOOTSTRAP=0
      - "ETH1_RPC_URL=https://main-light.eth.linkpool.io"
    restart: unless-stopped
    image: "heimdalld.polygon.public.dappnode.eth:0.1.0"
  heimdallr:
    environment:
      - REST_SERVER=1
      - "ETH1_RPC_URL=https://main-light.eth.linkpool.io"
    build: *ref_0
    volumes:
      - "/home/meng/polygon/heimdall:/root/.heimdalld"
    ports:
      - "1317"
    depends_on:
      - heimdalld
    restart: unless-stopped
    image: "heimdallr.polygon.public.dappnode.eth:0.1.0"
  bor:
    build:
      args:
        UPSTREAM_VERSION: v0.2.6
      context: ./build/bor
      dockerfile: Dockerfile
    environment:
      - SNAPSHOT_DATE=2021-06-22
      - BOOTSTRAP=0
    volumes:
      - "/home/meng/polygon/bor:/datadir"
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
      - "30303:30303/udp"
    depends_on:
      - heimdallr
    restart: unless-stopped
    image: "bor.polygon.public.dappnode.eth:0.1.0"
volumes:
  heimdall: {}
  bor: {}
